FROM datamechanics/spark:3.1-latest

COPY target/scala-project-1.0-SNAPSHOT.jar /app/scala-project-1.0-SNAPSHOT.jar

CMD ["spark-submit", "--class", "com.bouitamine.App", "--master", "local[*]", "/app/scala-project-1.0-SNAPSHOT.jar"]